# Generated by Django 2.2.14 on 2020-07-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrot_test',
            name='wetness',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
