# Generated by Django 2.2.14 on 2020-07-22 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_carrot_test_wetness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrot_test',
            old_name='Blue',
            new_name='blue',
        ),
        migrations.RenameField(
            model_name='carrot_test',
            old_name='Green',
            new_name='green',
        ),
        migrations.RenameField(
            model_name='carrot_test',
            old_name='Red',
            new_name='red',
        ),
    ]
