# Generated by Django 2.2.12 on 2020-08-02 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200722_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('temperature', models.FloatField()),
                ('wetness', models.FloatField()),
                ('HP', models.FloatField()),
                ('award', models.FloatField()),
                ('end_status', models.BooleanField()),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.DeleteModel(
            name='Carrot_test',
        ),
    ]
