# Generated by Django 2.2.12 on 2020-08-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20200802_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrot',
            name='HP',
        ),
    ]
