# Generated by Django 2.2.14 on 2020-08-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20200817_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrot',
            name='award',
            field=models.FloatField(null=True),
        ),
    ]
