# Generated by Django 2.2.14 on 2020-08-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20200823_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrot',
            name='award',
        ),
    ]
