# Generated by Django 2.2.14 on 2020-08-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_remove_carrot_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrot',
            name='award',
            field=models.FloatField(null=True),
        ),
    ]
