# Generated by Django 2.2.14 on 2020-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_carrot_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrot',
            name='award',
            field=models.FloatField(default=0, null=True),
        ),
    ]
